services:
    web3signer:
        container_name: "ws-web3signer-eth1"
        image: "consensys/web3signer:develop"
        environment:
          - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5005
        command: --config-file=/var/config/config.yaml eth1
        volumes:
        - ./config:/var/config
        ports:
        - "9000:9000"
        - "5005:5005" # Enable for debugging
        networks:
        - w3s-eth1

networks:
  w3s-eth1: {}