version: '3.8'

services:
  web3signer_migrations:
    image: consensys/web3signer:develop
    volumes:
      - ./migrations:/flyway/sql
    entrypoint: ["sh", "-c", "rm /flyway/sql/*.sql; cp /opt/web3signer/migrations/postgresql/*.sql /flyway/sql/; echo 'sql files copied!'"] 

  db:
    image: docker.io/bitnami/postgresql:14
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=web3signer
      - POSTGRES_PORT_NUMBER=5432 
    ports:
      - '5432:5432'
    networks:
      - testnet
    volumes: 
      - dbdata:/bitnami/postgresql
    depends_on:
      web3signer_migrations:
        condition: service_completed_successfully

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/web3signer -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql:ro
    depends_on:
      db:
        condition: service_started
      web3signer_migrations:
        condition: service_completed_successfully
    networks:
      - testnet

  web3signer:
    image: consensys/web3signer:develop
    command: --config-file=/var/config/config.yaml eth2
    volumes:
      - ./config:/var/config
    ports:
      - "9000:9000"
    networks:
      - testnet
    depends_on:
      flyway:
        condition: service_completed_successfully        

volumes:
  dbdata:

networks:
  testnet:
    name: pg_w3s_network
